name: github pages

on:
  schedule:
    # JSTで 毎週日曜 00:30 に設定
    # 5番目に0（日曜日）を指定
    - cron: 30 14 * * 0
  repository_dispatch:
    types: [check-link]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Use Node.js
        uses: actions/checkout@v2
        with:
          node-version: 14.x

      - name: npm install
        run: npm install

      - name: npx gulp
        run: npx gulp

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist