name: github pages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: 14.x
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/checkout@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install
        run: npm install
      - name: npx gulp
        run: npx gulp

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist